"""v2 additions for gen_synthetic.py, written after v1 scored 4/10 genuine posts as cringe and confused
hustle_guru / ai_thread_bro with neighbours on hand-written test A. NOTE: that means test A informed these
templates and is no longer a blind test; test B (test_blind.py) was written before this file and is the clean one.

New pieces are inserted BEFORE each class's two held-out pieces, so the validation split stays unseen.
"""
EXTRA = {
    "genuine": (
        # hooks
        ["Congrats to {name} on defending the thesis today. Long road, and well deserved.",
         "{name} shipped the first version of the {tool} plugin this week. Small team, real users, already found two bugs.",
         "I was laid off on Tuesday. I'll take a week, then start looking at roles in {field}. An intro or two would help.",
         "Looking for a role in {field}. {n} years of experience, mostly {tool}. Happy to do a paid trial project.",
         "Small thing I learned this week: our {thing} was caused by a default setting in {tool}. One line fixed it.",
         "Notes from the {field} meetup last night, for anyone who couldn't make it:",
         "We closed the office early on Friday for {name}'s farewell. Seven years is a long time. Good luck at the new place.",
         "PSA: our support line is closed Monday for the holiday. Tickets will be answered Tuesday morning.",
         "Ran my first {n}K yesterday. Slow, but I finished, and my knees only complained a little.",
         "Has anyone tried {tool} for {field}? I'm weighing it against what we use now and would like real experiences.",
         "The food drive collected {k} kg last weekend, about twice last year. Thanks to the volunteers and to {name} for the van.",
         "Teaching tip that worked for my class: I stopped grading homework and started grading the corrections instead.",
         "Our team is hiring one {role}. Remote in Europe, the salary range is in the description, and there are two interview rounds.",
         "My mother was in hospital for a week and I learned how little our carer's leave policy said. We changed it.",
         "Postmortem of last week's outage. Short version: an expired certificate, and nobody owned the renewal.",
         "Reading {name}'s article on {field} this morning. Two points I agree with and one I don't.",
         "Quick question for people who manage {field} teams: how do you handle on-call after a bad release?",
         "We turned down a large client this week because the scope didn't fit our team. Notes on how we decided.",
         "Thank you to the {n} people who stayed late on Thursday to get the release out. Pizza is on me Monday.",
         "I'm starting a new role at {company} on Monday. I'll miss the people I'm leaving the most.",
         "Three books I finished this year and one line on each, so you can skip the ones you don't need.",
         "Interviewed {n} candidates this month. What separated the good ones was not the answers, it was the questions they asked.",
         "The bug was a timezone conversion. It only showed up on the last day of the month, in one region. Took us {dur}.",
         "Our office moved to a four-day week in January. Six months of numbers, with the caveats:"],
        # middles
        ["We measured it before and after and the table is below.",
         "It was mostly luck and a lot of small fixes, not one clever idea.",
         "I don't know whether it generalises, so please treat it as one team's experience.",
         "The details are in the doc linked at the top, including what didn't work.",
         "If you're in the same position, my inbox is open.",
         "We wrote down what we would do differently next time.",
         "Attendance was about {n} people, and the talks were recorded.",
         "It cost more than we planned, but the cost was mostly time, not money.",
         "Happy to answer questions, and happy to be told I'm wrong.",
         "Support tickets on that page dropped by about {pct}% afterwards."],
        # closers
        ["Thanks for reading.", "Happy to share more if it helps.", "More soon.", "Any corrections welcome.",
         "That's all for now.", "If you're nearby, come and say hi.", "Have a good weekend.", "Details in the comments."],
    ),
    "hustle_guru": (
        ["Your alarm is not the enemy. Your excuses are.",
         "Nobody remembers who slept in.",
         "You don't have a time problem. You have a priorities problem.",
         "Success is rented, and the rent is due every day.",
         "They'll call you obsessed until you win.",
         "Stop waiting for motivation. Motivation is a mood.",
         "Comfort is the silent killer of ambition.",
         "Same 24 hours. Different outcomes. Choose."],
        ["Winners simply refuse to waste the time.", "Show up when it's dark, cold and inconvenient.", "Pay with sweat, early mornings and the word no.", "The gym at 5AM is quiet because champions are busy."],
        ["Keep working.", "No days off.", "Go.", "Decide."],
    ),
    "ai_thread_bro": (
        ["These {n} free AI tools will make you 10x more productive. Number 3 is insane.",
         "I spent 100 hours testing every AI tool so you don't have to. Here are the only {n} you need.",
         "AI won't take your job. Someone using AI will. Here are {n} tools to be that someone.",
         "ChatGPT is not a search engine. Here's the {n}-step prompt framework for 10x better answers:",
         "Nobody is talking about this AI workflow that saves {n} hours a week.",
         "I built a full website in 10 minutes using only AI. No code. Here's how:",
         "Stop writing emails manually. These {n} AI tools will do it for you.",
         "The AI cheat sheet I wish I'd had a year ago: {n} prompts for marketing, sales and hiring."],
        ["Prompt 1: 'Act as a senior {field} consultant and...'", "Tool 3 will blow your mind.", "Here's the workflow, step by step (save it):", "No experience needed, just paste this."],
        ["Retweet to save this.", "Bookmark this thread.", "Follow for more AI tips.", "Which will you try first?"],
    ),
    "engagement_bait": (
        ["Which is harder: managing up or managing down? Vote below!",
         "Do you check email first thing in the morning? Comment 1 for yes, 2 for no.",
         "Tag your favourite manager below. Let's spread some positivity today! 💙",
         "Only real ones remember dial-up. Drop a 🙋 if you do.",
         "If you agree that recruiters should share the salary range, give this a like.",
         "Comment 'PLAYBOOK' and I'll send you the full {field} playbook in your DMs.",
         "What's your one non-negotiable at work? Share it and follow for more.",
         "Does your boss reply to email on Sunday? Yes or no. Let's see the numbers. 👇"],
        ["I'll share the results next week.", "Every comment gets a reply.", "Repost to help a friend get their next role.", "Let's get this to {k} people."],
        ["Drop your answer below.", "Let's see who's honest.", "Follow for more.", "Share with your network."],
    ),
    "fake_parable": (
        ["My father-in-law handed me an envelope when I told him I was quitting my job.",
         "A new hire spilled coffee on our CEO's laptop. Everyone froze.",
         "I sat next to an elderly woman on a {n}-hour flight who knitted the whole time.",
         "The cleaner at my first office said good morning to everyone by name.",
         "An intern corrected me in front of the whole team.",
         "My 8-year-old came home with a C and shrugged.",
         "I rejected a candidate because his shoes were scuffed."],
        ["Inside was a photo of his first shop and a note: 'Fear is just excitement without the breathing.'", "The CEO laughed and said, 'Great. Now I finally have an excuse to buy a new one.'", "She looked at me and said, 'Stitch by stitch, dear.'", "When the company went under, he was the only one who checked on me.", "Two years later he became my biggest client. He never mentioned it."],
        ["I've never forgotten it.", "Kindness pays off.", "Judge less. Listen more.", "That's the day I understood what culture is."],
    ),
    "humblebrag": (
        ["Woke up to the news that our team's paper won Best Paper. Honestly stunned.",
         "Just a casual reminder that {n} years ago I was sleeping on a friend's couch.",
         "I can't say much yet, but the last {n} months have been the most incredible of my career.",
         "I usually avoid talking about awards, but this one is special: {award}.",
         "Honoured to be asked by three universities to give guest lectures this fall.",
         "Life update: I became a partner today. I don't say this to brag."],
        ["I just do the work I love, and somehow it keeps being noticed.", "To everyone who doubted me: thank you for the motivation.", "Still surprised anyone wants to hear from me.", "To my mentors: I owe you everything."],
        ["So thankful for this journey. 🙏", "Deeply humbled.", "Ready to learn.", "Grateful beyond words."],
    ),
    "buzzword_salad": (
        ["Delighted to share that our team has operationalised a bold, {buzz} framework for the orchestration of {noun}.",
         "The future belongs to organisations that harness agility and re-imagine {noun} through a {buzz} lens.",
         "In today's disruptive landscape, thought leadership means leveraging {buzz} insights to catalyse change at scale.",
         "Thrilled to step into my new role as Lead, Strategic Value Enablement, championing {buzz} solutions.",
         "It's time to double down on core competencies while pivoting to a {buzz}, insight-led operating paradigm."],
        ["We are unlocking exponential value for all stakeholders.", "It is about moving the needle on {buzz} {noun}.", "The journey towards a resilient, future-ready {noun} has only just begun."],
        ["#transformation", "Onwards.", "Let's connect.", "Exciting times ahead."],
    ),
    "shameless_plug": (
        ["My agency has {n} openings for {month}. We do {field} for B2B founders. Message me.",
         "Launching tomorrow: {course}. Early-bird price ends at midnight.",
         "Just released my new ebook. Grab your copy at the link in my bio.",
         "Struggling to get leads? We book {n} qualified meetings a month or you don't pay.",
         "Our webinar is next Thursday. Free to attend, limited seats. Register now.",
         "I'm opening {n} spots in my coaching program this quarter."],
        ["Bonus: a free call for the first {n} buyers.", "Serious applicants only.", "Includes 40 templates and lifetime updates.", "Apply for a free audit today."],
        ["Link in the comments.", "Register below.", "DM me to start.", "Book a call."],
    ),
}
NAMES = ["Priya", "Marcus", "Aisha", "Tomás", "Wei", "Sofia", "Daniel", "Ngozi", "Ravi", "Elena"]
